# Multiplication between N-dimensional Arrays


In this notebook, we describe the techniques for multiplying N-dimensional arrays (ndarray) using NumPy. Specifically, we describe the following types of multiplications.

- Element-wise multiplication (Hadamard product)
- Dot product
- Matrix multiplication


In [1]:
import numpy as np

## Element-wise multiplication (Hadamard product)

The element-wise product or Hadamard product is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands, where each element i, j is the product of elements i, j of the original two matrices.

We can use the following two NumPy techniques for performing element-wise multiplication.

- *
- np.multiply

We will get the same result by using both techniques.

In [2]:
# Create a 2D matrix
a = np.array([[2, 2], [2, 2]]) 
print("Matrix a:\n", a)
print("\nShape of a: ", a.shape)

# Create another 2D matrix
b = np.array([[4, 4], [4, 4]])  
print("\nMatrix b:\n", b)
print("\nShape of b:", b.shape)

# Element-wise multiplication using *
c = a * b
print("\na * b:\n", c)

# Element-wise multiplication using np.multiply
d = np.multiply(a, b)
print("\nnp.multiply(a, b):\n", d)

Matrix a:
 [[2 2]
 [2 2]]

Shape of a:  (2, 2)

Matrix b:
 [[4 4]
 [4 4]]

Shape of b: (2, 2)

a * b:
 [[8 8]
 [8 8]]

np.multiply(a, b):
 [[8 8]
 [8 8]]



## Dot product:

The dot product is an algebraic operation that takes two same-sized **vectors** (dimension 1D) and returns a single number.


For computing a dot product between two vectors, we use the **np.dot** function.

The np.dot function can also be used for computing the dot product between two ndarrays (matrices). This is shown later.

In [3]:
# Create a vector
a = np.array([2, 2, 2]) 
print("Vector a: ", a)
print("Shape of a: ", a.shape)

# Create another vector
b = np.array([4, 4, 4])  
print("\nVector b: ", b)
print("Shape of b:", b.shape)


# Dot product of a and b
c = np.dot(a, b) 
print("\nnp.dot(a, b): ", c)

Vector a:  [2 2 2]
Shape of a:  (3,)

Vector b:  [4 4 4]
Shape of b: (3,)

np.dot(a, b):  24


## Matrix Multiplication

It is the **matrix version of the dot product**. Unlike the scalar-valued result of a dot product, the result of matrix multiplication is a matrix.


For performing matrix multiplication, we can use
- np.matmul function
- @ oprator 

The @ operator performs the same task the np.matmul peforms. However, it is available only in python 3.5+

In [4]:
# Create a 2D matrix
a = np.array([[2, 2], [2, 2]]) 
print("Matrix a:\n", a)
print("\nShape of a: ", a.shape)

# Create another 2D matrix
b = np.array([[4, 4], [4, 4]])  
print("\nMatrix b:\n", b)
print("\nShape of b:", b.shape)

# np.matmul
d = np.matmul(a, b)
print("\nnp.matmul(a, b):\n", d)

# @
e = a @ b
print("\na @ b:\n", e)

Matrix a:
 [[2 2]
 [2 2]]

Shape of a:  (2, 2)

Matrix b:
 [[4 4]
 [4 4]]

Shape of b: (2, 2)

np.matmul(a, b):
 [[16 16]
 [16 16]]

a @ b:
 [[16 16]
 [16 16]]


## Comparison: Dot Product vs. Matrix Multiplication

The np.dot and np.matmul (and @) functions give the **same result**. However, there is an important difference.

- The np.dot function behaves differently for matrices with dimensions higher than 2D. In such a case, np.matmul should be used.

Following guideline could be useful for selecting a suitable function.
- np.dot: for computing a dot product between two 1D vectors 
- np.matmul and @: for computing a matrix multiplication between two matrices (2D or higher)



## Example: Two 2D Matrices 

We will see that np.dot, np.matmul, and @ **behave similarly** when the dimension of the matrices is <=2D.

In [5]:
a = np.array([[2, 2], [2, 2]]) 
print("Matrix a:\n", a)
print("\nShape of a: ", a.shape)

b = np.array([[4, 4], [4, 4]])  
print("\nMatrix b:\n", b)
print("\nShape of b:", b.shape)

# np.dot
c = np.dot(a, b) 
print("\nnp.dot(a, b):\n", c)

# np.matmul
d = np.matmul(a, b)
print("\nnp.matmul(a, b):\n", d)

# @
e = a @ b
print("\na @ b:\n", e)

Matrix a:
 [[2 2]
 [2 2]]

Shape of a:  (2, 2)

Matrix b:
 [[4 4]
 [4 4]]

Shape of b: (2, 2)

np.dot(a, b):
 [[16 16]
 [16 16]]

np.matmul(a, b):
 [[16 16]
 [16 16]]

a @ b:
 [[16 16]
 [16 16]]


## Example: Two 3D Matrices 

We will see that the np.dot **behaves differently** than np.matmul or @ when the dimension of the matrices is larger than 2D. 

Note: The np.dot function works for high dimensional matrices as follows.
If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

dot(a,b)[i,j,k,m]=sum(a[i,j,:]∗b[k,:,m])

In [6]:
a = np.ones(shape=(3, 2, 2), dtype=np.float32) * 2
print("Matrix a:\n", a)
print("\nShape of a: ", a.shape)

b = np.ones(shape=(3, 2, 2), dtype=np.float32) * 4
print("\nMatrix b:\n", b)
print("\nShape of b: ", b.shape)

# np.dot
c = np.dot(a, b) 
print("\nnp.dot(a, b):\n", c)
print("\nShape of np.dot(a, b): ", c.shape)

# np.matmul
d = np.matmul(a, b)
print("\nnp.matmul(a, b):\n", d)
print("\nShape of np.matmul(a, b): ", d.shape)

# @
e = a @ b
print("\na @ b:\n", e)
print("\nShape of a @ b: ", e.shape)

Matrix a:
 [[[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]]

Shape of a:  (3, 2, 2)

Matrix b:
 [[[4. 4.]
  [4. 4.]]

 [[4. 4.]
  [4. 4.]]

 [[4. 4.]
  [4. 4.]]]

Shape of b:  (3, 2, 2)

np.dot(a, b):
 [[[[16. 16.]
   [16. 16.]
   [16. 16.]]

  [[16. 16.]
   [16. 16.]
   [16. 16.]]]


 [[[16. 16.]
   [16. 16.]
   [16. 16.]]

  [[16. 16.]
   [16. 16.]
   [16. 16.]]]


 [[[16. 16.]
   [16. 16.]
   [16. 16.]]

  [[16. 16.]
   [16. 16.]
   [16. 16.]]]]

Shape of np.dot(a, b):  (3, 2, 3, 2)

np.matmul(a, b):
 [[[16. 16.]
  [16. 16.]]

 [[16. 16.]
  [16. 16.]]

 [[16. 16.]
  [16. 16.]]]

Shape of np.matmul(a, b):  (3, 2, 2)

a @ b:
 [[[16. 16.]
  [16. 16.]]

 [[16. 16.]
  [16. 16.]]

 [[16. 16.]
  [16. 16.]]]

Shape of a @ b:  (3, 2, 2)
