# Array Broadcasting

NumPy provides a mechanism for performing mathematical operations on arrays of unequal shapes. This mechanism is known as array broadcasting or broadcasting.


The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. 

Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. 



## General Broadcasting Rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when

- they are equal, or

- one of them is 1

If these conditions are not met, following exception is thrown: 

        ValueError: operands could not be broadcast together  

It indicates that the arrays have incompatible shapes. The size of the resulting array is the size that is not 1 along each axis of the inputs.


For more information: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [1]:
import numpy as np

In [2]:
'''
Dimensions of the two arrays are not compatible
'''

x = np.array([1,3,5])
y = np.array([2,4])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

print(x+y)


x dimension:  (3,)
y dimension:  (2,)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [3]:
'''
Dimensions of the two arrays are compatible
- because the dimension of the 2nd array is 1
Here, dimensions with size 1 are stretched or “copied” to match the other.
'''

x = np.array([1,3,5])
y = np.array([2,])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

print(x+y)

x dimension:  (3,)
y dimension:  (1,)
[3 5 7]


In [4]:
'''
Dimensions of the two arrays are compatible
- because the right-most dimensions are  equal

Here the lining up the sizes of the trailing axes of these arrays according to the broadcast rules, 
shows that they are compatible.
'''

x = np.array([[1, 3, 5], [7, 8, 9]])
y = np.array([2, 1, 3])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

print(x+y)

x dimension:  (2, 3)
y dimension:  (3,)
[[ 3  4  8]
 [ 9  9 12]]


## Outer Product

Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays. The following example shows an outer addition operation of two 1-d arrays:

Here the newaxis index operator inserts a new axis into x, making it a two-dimensional (4 x 1) array. Combining the 4x1 array with y, which has shape (3, ), yields a (4 x 3) array.

In [5]:
x = np.array([0.0, 10.0, 20.0, 30.0])
y = np.array([1.0, 2.0, 3.0])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

# add a new axis
x = x[:, np.newaxis]

print("\nx dimension: ", x.shape)

print(x + y)

x dimension:  (4,)
y dimension:  (3,)

x dimension:  (4, 1)
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


Alternatively, we may insert a new axis into y, making it a two-dimensional (3 x 1) array. 

Then, we combine the array x with shape (4, ) with the new y, yielding a (3 x 4) array.

In [6]:
x = np.array([0.0, 10.0, 20.0, 30.0])
y = np.array([1.0, 2.0, 3.0])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

# add a new axis
y = y[:, np.newaxis]

print("\ny dimension: ", y.shape)

print(x + y)

x dimension:  (4,)
y dimension:  (3,)

y dimension:  (3, 1)
[[ 1. 11. 21. 31.]
 [ 2. 12. 22. 32.]
 [ 3. 13. 23. 33.]]
